#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const repl = require('repl');
const Fulcrum = require('./dist');

require('source-map-support').install();

const fileRoot = path.join('.', 'test', 'fixtures');

const dataSource = new Fulcrum.DataSource().add(new Fulcrum.FileDataSource(fileRoot));

// import the API into the global scope to make it easier
for (var prop in Fulcrum) {
  if (Fulcrum.hasOwnProperty(prop)) {
    global[prop] = Fulcrum[prop];
  }
}

const formJson = JSON.parse(fs.readFileSync('./test/fixtures/forms/18300cfb-20e3-4e8b-9aef-878636b09ac4.json')).form;
const recordJson = JSON.parse(fs.readFileSync('./test/record.json')).record;

global.form = new Fulcrum.Form(formJson);
global.form.load(dataSource, () => {});

global.record = new Fulcrum.Record(global.form, recordJson);

repl.start('fulcrum> ');
